import { Router, Response } from 'express';
import PDFDocument from 'pdfkit';
import { query } from '../config/database';
import { authenticate } from '../middleware/auth';
import { AuthRequest, AuditResults } from '../types';

const router = Router();

// generate pdf report for an audit
router.get('/:id/pdf', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    const result = await query(
      `SELECT a.*, m.name as model_name, m.framework
       FROM audits a
       LEFT JOIN ml_models m ON a.model_id = m.id
       WHERE a.id = $1`,
      [req.params.id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Audit not found' });
    }

    const audit = result.rows[0];

    if (audit.status !== 'completed') {
      return res.status(400).json({ error: 'Audit not completed yet' });
    }

    // create pdf
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=audit-${audit.id}.pdf`);

    doc.pipe(res);

    // header
    doc.fontSize(24).text('GUARDIAN Audit Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Generated: ${new Date().toISOString()}`, { align: 'center' });
    doc.moveDown(2);

    // model info
    doc.fontSize(16).text('Model Information');
    doc.moveDown(0.5);
    doc.fontSize(11)
      .text(`Name: ${audit.model_name}`)
      .text(`Framework: ${audit.framework}`)
      .text(`Audit Type: ${audit.audit_type}`)
      .text(`Audit Date: ${new Date(audit.created_at).toLocaleDateString()}`);
    doc.moveDown(1.5);

    // scores section
    doc.fontSize(16).text('Compliance Scores');
    doc.moveDown(0.5);
    
    const scores = [
      { label: 'CERN Compliance', value: audit.cern_compliance },
      { label: 'Bias Score', value: audit.bias_score },
      { label: 'Fairness Score', value: audit.fairness_score }
    ];

    scores.forEach(score => {
      const val = score.value !== null ? `${(score.value * 100).toFixed(1)}%` : 'N/A';
      doc.fontSize(11).text(`${score.label}: ${val}`);
    });
    doc.moveDown(1.5);

    // detailed results
    const results: AuditResults = audit.results || {};

    if (results.bias_metrics) {
      doc.fontSize(16).text('Bias Metrics');
      doc.moveDown(0.5);
      doc.fontSize(11)
        .text(`Demographic Parity: ${results.bias_metrics.demographic_parity?.toFixed(4) || 'N/A'}`)
        .text(`Equalized Odds: ${results.bias_metrics.equalized_odds?.toFixed(4) || 'N/A'}`)
        .text(`Disparate Impact: ${results.bias_metrics.disparate_impact?.toFixed(4) || 'N/A'}`);
      doc.moveDown(1.5);
    }

    if (results.fairness_metrics) {
      doc.fontSize(16).text('Fairness Metrics');
      doc.moveDown(0.5);
      doc.fontSize(11)
        .text(`Statistical Parity Difference: ${results.fairness_metrics.statistical_parity_difference?.toFixed(4) || 'N/A'}`)
        .text(`Equal Opportunity Difference: ${results.fairness_metrics.equal_opportunity_difference?.toFixed(4) || 'N/A'}`)
        .text(`Average Odds Difference: ${results.fairness_metrics.average_odds_difference?.toFixed(4) || 'N/A'}`);
      doc.moveDown(1.5);
    }

    if (results.cern_compliance_details) {
      doc.fontSize(16).text('CERN Compliance Details');
      doc.moveDown(0.5);
      const details = results.cern_compliance_details;
      doc.fontSize(11)
        .text(`Transparency: ${(details.transparency_score * 100).toFixed(1)}%`)
        .text(`Accountability: ${(details.accountability_score * 100).toFixed(1)}%`)
        .text(`Fairness: ${(details.fairness_score * 100).toFixed(1)}%`)
        .text(`Safety: ${(details.safety_score * 100).toFixed(1)}%`);
      doc.moveDown(1.5);
    }

    // recommendations
    if (results.recommendations && results.recommendations.length > 0) {
      doc.fontSize(16).text('Recommendations');
      doc.moveDown(0.5);
      results.recommendations.forEach((rec, i) => {
        doc.fontSize(11).text(`${i + 1}. ${rec}`);
      });
      doc.moveDown(1.5);
    }

    // warnings
    if (results.warnings && results.warnings.length > 0) {
      doc.fontSize(16).fillColor('red').text('Warnings');
      doc.moveDown(0.5);
      doc.fillColor('black');
      results.warnings.forEach((warn, i) => {
        doc.fontSize(11).text(`${i + 1}. ${warn}`);
      });
    }

    // footer
    doc.moveDown(2);
    doc.fontSize(9).fillColor('gray')
      .text('This report was generated by GUARDIAN - ML Audit Platform', { align: 'center' })
      .text('For CERN AI Ethics Compliance', { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('PDF generation error:', err);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

// get report data as json (for frontend charts)
router.get('/:id/data', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    const result = await query(
      `SELECT a.*, m.name as model_name, m.framework
       FROM audits a
       LEFT JOIN ml_models m ON a.model_id = m.id
       WHERE a.id = $1`,
      [req.params.id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Audit not found' });
    }

    const audit = result.rows[0];

    // format data for charts
    const chartData = {
      scores: {
        labels: ['CERN Compliance', 'Bias Score', 'Fairness Score'],
        values: [
          audit.cern_compliance || 0,
          audit.bias_score || 0,
          audit.fairness_score || 0
        ]
      },
      biasMetrics: audit.results?.bias_metrics || null,
      fairnessMetrics: audit.results?.fairness_metrics || null,
      featureImportance: audit.results?.explainability?.feature_importance || null,
      topFeatures: audit.results?.explainability?.top_features || [],
      complianceDetails: audit.results?.cern_compliance_details || null
    };

    res.json({ audit, chartData });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch report data' });
  }
});

export default router;
